# Write your code here :-)
print('Hello World!')
print('What is your Name')
myName = input()
print('Its nice to meet you ' + myName)
print('The length of your name is:')
print(len(myName))
print('What is your age?')
myAge = input()
print('You will be ' + str(int(myAge) +1) + ' in a year!')
